# Generated by Django 2.2.9 on 2020-04-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=254)),
                ('node', models.CharField(max_length=254)),
                ('create_date', models.DateTimeField()),
                ('deleted', models.BooleanField()),
            ],
        ),
    ]
