# Generated by Django 2.2.9 on 2020-04-16 22:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=254)),
                ('node', models.CharField(max_length=254)),
                ('create_date', models.DateTimeField(editable=False, null=True)),
                ('scrape_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_checked', models.DateTimeField(null=True)),
                ('stale', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=True)),
                ('query', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recycler.Query')),
            ],
        ),
        migrations.CreateModel(
            name='DeletedRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_found', models.DateTimeField(auto_now_add=True)),
                ('is_interesting', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('note', models.TextField()),
                ('repo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recycler.Repo')),
            ],
        ),
    ]
