# Generated by Django 2.2.9 on 2020-04-16 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recycler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='repo',
            name='deleted',
        ),
        migrations.AddField(
            model_name='repo',
            name='last_checked',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='repo',
            name='stale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='repo',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='DeletedRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_found', models.DateTimeField(auto_now_add=True)),
                ('is_interesting', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('note', models.TextField()),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Recycler.Repo')),
            ],
        ),
        migrations.AddField(
            model_name='repo',
            name='query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Recycler.Query'),
        ),
    ]
