# Generated by Django 2.2.9 on 2020-04-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recycler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='repo',
            name='node',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='repo',
            name='url',
            field=models.CharField(max_length=256),
        ),
    ]
